pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn clean verify
      }
      
    }
   
        stage('Hello') {
            agent {
        docker { image 'Hello world' }
            }
          steps {
                echo 'Hello World'
            }
         }
    
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node install'
      }
    }
  }
}
